### ISSUE TITLE
Connection failures not handled gracefully

### ISSUE THREAD

**Issue by ascl00** [k3erg/marantz-denon-telnet#3]
When an failure to connect happens, it is uncaught and causes node.js to barf:
```
events.js:187
      throw err;
      ^

Error: Unhandled "error" event. (Cannot connect)
    at Telnet.emit (events.js:185:19)
    at Socket.socket.setTimeout (C:\Users\Nick\github\roon-extension-denon-telnet\node_modules\telnet-client\lib\index.js:76:16)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at Socket.emit (events.js:207:7)
    at Socket._onTimeout (net.js:402:8)
    at ontimeout (timers.js:488:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:283:5)
```

The solution is pretty straight forward, we need to catch the error with a handler. The below patch does this, although it is unclear to me if the best behaviour is to drop the entry from the cmdQueue or not:
```
@@ -82,10 +84,19 @@ MarantzDenonTelnet.prototype.sendNextTelnetCueItem = function() {
         if (!this.connection) {
             this.connection = new telnet();
             this.connection.on('connect', function() {
                 mdt.sendNextTelnetCueItem();
             });
+            this.connection.on('error', function() {
+                // There must be an item on the cmdCue, else we wouldn't be here...
+                // and node.js barfs if we don't catch this error. So lets catch it
+                // and use the first item in the cmdCue's error handler.
+                // Only quetion is, should we remove it from the queue or not?
+                mdt.cmdCue[0].callback("Failed to connect", null);
+                mdt.connection.end();
+                mdt.connection = null;
+            });
             this.connection.connect(this.connectionparams);
         } else {
             var item = this.cmdCue.shift();
             var isRequestCommand = (item.cmd.substr(-1) === '?');
             this.connection.send(item.cmd, {timeout: (isRequestCommand ? this.connectionparams.timeout : 10)}, function(error, data) {
```

**Comment by k3erg** [comment]
@ascl00 Txs
True, and it happens quite often – added.
